services:
  mongodb:
    image: mongo:6
    container_name: mongo-usuarios
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
